name: .NET Build

on:
    push:
      branches: [ main ]
      paths:
        - 'dotnet/**'
    pull_request:
      branches: [ main ]
      paths:
        - 'dotnet/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dotnet

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore