name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            if (!title || title.trim().length < 5) {
              core.setFailed("PR title is too short or missing.");
            }