name: Python Build

on:
  push:
    branches: [ main ]
    paths:
      - 'python/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'python/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Validate pyproject.toml structure
        run: poetry check

      - name: Regenerate poetry.lock to check sync
        run: poetry lock

      - name: Fail if poetry.lock is out of sync
        run: |
          git diff --exit-code poetry.lock || (
            echo "::error file=poetry.lock::poetry.lock is not up to date with pyproject.toml. Run 'poetry lock' and commit the result."
            exit 1
          )
            
      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Lint code
        run: poetry run ruff check .

      - name: Build package
        run: poetry build
