name: Python Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python

    permissions:
      contents: write # Required to upload release artifacts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Validate tag format
        run: |
          if [[ ! "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9\.]+)?$ ]]; then
            echo "Invalid tag format: $GITHUB_REF_NAME"
            echo "Expected: v<MAJOR>.<MINOR>.<PATCH> (e.g., v1.2.3 or v1.2.3-beta.1)"
            exit 1
          fi

      - name: Set version from tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "Setting poetry version to $VERSION"
          poetry version $VERSION

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build package
        run: poetry build

      - name: Upload dist artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            python/dist/*.whl